-- Run this in SQL*Plus as the HOTEL schema user.
-- Example:
--   SQL> @db_hotel_constraints_services.sql

SET SERVEROUTPUT ON;
SET DEFINE OFF;

PROMPT === 1) BOOKINGS: add columns + constraints ===

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE bookings ADD (guests_count NUMBER(2))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE bookings ADD (breakfast_included CHAR(1))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE bookings MODIFY (guests_count NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-1442, -1451) THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE bookings MODIFY (breakfast_included NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-1442, -1451) THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE bookings ADD CONSTRAINT chk_bookings_guests_count CHECK (guests_count BETWEEN 1 AND 5)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE bookings ADD CONSTRAINT chk_bookings_breakfast_flag CHECK (breakfast_included IN (''Y'',''N''))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

PROMPT Creating trigger to enforce CHECK_OUT > CHECK_IN (when both present)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER trg_bookings_dates
    BEFORE INSERT OR UPDATE OF check_in, check_out ON bookings
    FOR EACH ROW
    BEGIN
      IF :NEW.check_in IS NOT NULL AND :NEW.check_out IS NOT NULL THEN
        IF :NEW.check_out <= :NEW.check_in THEN
          RAISE_APPLICATION_ERROR(-20001, ''Check-out date must be after check-in date.'');
        END IF;
      END IF;
    END;';
END;
/

PROMPT === 2) GUESTS: add GENDER + constraints (phone/email/gender) ===

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE guests ADD (gender VARCHAR2(10))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE guests MODIFY (gender NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-1442, -1451) THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE guests ADD CONSTRAINT chk_guests_gender CHECK (UPPER(gender) IN (''MALE'',''FEMALE'',''OTHER''))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE guests ADD CONSTRAINT chk_guests_phone_digits CHECK (REGEXP_LIKE(phone, ''^[0-9]{10}$''))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE guests ADD CONSTRAINT chk_guests_email_format CHECK (email IS NULL OR REGEXP_LIKE(email, ''^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$''))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

PROMPT === 3) SERVICES: catalog + booking line items ===

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE service_catalog (
      service_code   VARCHAR2(30) PRIMARY KEY,
      service_name   VARCHAR2(100) NOT NULL,
      unit_price     NUMBER(10,2) NOT NULL,
      pricing_model  VARCHAR2(30) NOT NULL,
      active         CHAR(1) DEFAULT ''Y'' NOT NULL,
      CONSTRAINT chk_service_catalog_active CHECK (active IN (''Y'',''N''))
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE booking_service_items (
      item_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      booking_id    NUMBER NOT NULL,
      service_code  VARCHAR2(30) NOT NULL,
      service_date  DATE,
      pax           NUMBER(2),
      quantity      NUMBER(6) DEFAULT 1 NOT NULL,
      unit_price    NUMBER(10,2) NOT NULL,
      amount        NUMBER(10,2) NOT NULL,
      created_at    DATE DEFAULT SYSDATE NOT NULL
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE booking_service_items ADD CONSTRAINT fk_bsi_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2261 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE booking_service_items ADD CONSTRAINT fk_bsi_service FOREIGN KEY (service_code) REFERENCES service_catalog(service_code)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2261 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE booking_service_items ADD CONSTRAINT chk_bsi_pax CHECK (pax IS NULL OR (pax BETWEEN 1 AND 5))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE booking_service_items ADD CONSTRAINT chk_bsi_quantity CHECK (quantity >= 1)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

PROMPT Seeding service catalog (prices you specified)
MERGE INTO service_catalog sc
USING (
  SELECT 'FOOD'    AS service_code, 'Lunch/Dinner/Room Service' AS service_name, 400 AS unit_price, 'PER_ORDER'        AS pricing_model FROM dual UNION ALL
  SELECT 'SPA'     AS service_code, 'Spa'                       AS service_name, 500 AS unit_price, 'PER_PERSON'       AS pricing_model FROM dual UNION ALL
  SELECT 'POOL'    AS service_code, 'Pool Access'               AS service_name,  50 AS unit_price, 'PER_PERSON_PER_DAY' AS pricing_model FROM dual UNION ALL
  SELECT 'BANQUET' AS service_code, 'Banquet Hall'              AS service_name,10000 AS unit_price, 'FLAT'             AS pricing_model FROM dual UNION ALL
  SELECT 'BREAKFAST' AS service_code, 'Breakfast'               AS service_name, 200 AS unit_price, 'PER_PERSON_PER_NIGHT' AS pricing_model FROM dual
) src
ON (sc.service_code = src.service_code)
WHEN MATCHED THEN
  UPDATE SET sc.service_name = src.service_name,
             sc.unit_price = src.unit_price,
             sc.pricing_model = src.pricing_model,
             sc.active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (service_code, service_name, unit_price, pricing_model, active)
  VALUES (src.service_code, src.service_name, src.unit_price, src.pricing_model, 'Y');
/

PROMPT === Done. Now update your Java code to compute totals using BOOKINGS + BOOKING_SERVICE_ITEMS + rules. ===
